[project]
name = "plate-cli"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "easyocr>=1.7.2",
    "prompt-toolkit>=3.0.52",
    "rich>=14.3.1",
    "ruff>=0.14.14",
    "selenium>=4.40.0",
    "ultralytics>=8.4.8",
]
